@URL = http://localhost:3000

GET {{URL}}

###
POST  {{URL}}/auth/login
Content-Type: application/json

{
    "email": "abdlzzcan@gmail.com",
    "password": "124"
}    

###
PATCH {{URL}}/6

{    
    "email": "abdlzzcan@gmail.com",
    "password": "1234"
}
